"""Update data room

Revision ID: 6af15a99da5f
Revises: aaee919a1085
Create Date: 2025-10-12 23:03:31.252280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6af15a99da5f'
down_revision: Union[str, Sequence[str], None] = 'aaee919a1085'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'data_room', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data_room', type_='unique')
    # ### end Alembic commands ###
